[package]
name = "slot_machine_hiyo"
version = "0.1.0"
authors = ["kareinonitsuke"]
edition = "2018"

[dependencies]
serenity = {version = "0.10.2"}
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
rand="0.6.5"
